### ISSUE TITLE
ROADMAP do sistema

### ISSUE THREAD

**Issue by Marlysson** [dayanamaia/sistema-health-track#2]
Encontrei esse sistema aqui no github, achei espetacular, boa interface e bom propósito.

VC tem algum roadmap das funcionalidades que o sistema terá?

API, front, tecnologias, funcionalidades...

Parabéns pelo sistema.

Uma dúvida, posso clonar esse sistema usando Django? :D

**Comment by dayanamaia** [comment]
Oi Marlysson,
Pode clonar!, usar a vontade. 
Gostei muito de fazer esse trabalho e ainda falta muita coisa rsrs.

É um trabalho acadêmico, no qual, tenho que usar Java e o banco de dados Oracle...
Segue o que tem e o que falta eu fazer:

**Front-End:**
Feito:
- Criação das telas responsivas HTML/CSS3: Tela Inicial / Cadastrar uma conta / Dashboard / Formulário de cadastro e listagem das categorias: Peso, Exercícios Físicos, Pressão Arterial, Glicose, Colesterol, Quantidade de Água ingerida e horas de sono.
- HTML/CSS/JS do menu;
- Validação dos formulários;
- Modal para avisar o usuário sobre a exclusão de um item;

O que Falta:
- Funcionalidade PWA;
- Animação das telas;
- Integrar API de clima tempo, de acordo com a localização;
- Tela de configuração da conta;
- Tela de Ajuda/FAQ;
- Tela 404

**Back-End**
Feito:
- Já tem a integração/CRUD de algumas categorias;
script das [tabelas](https://github.com/dayanamaia/script-sql-sistema-health-track);
- Login e Logout;
- Tela 404;

O que Falta:
- Falta fazer a integração do Dashboard.
- Cadastro do usuário - CRUD;
- Filtro dos itens das categorias: por tag e data;
- Paginação
